# Generated by Django 5.1.2 on 2024-11-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('repeat', models.JSONField(default=dict)),
                ('start_date', models.DateField()),
                ('time', models.TimeField()),
                ('command', models.CharField(max_length=10)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='api.channel')),
            ],
        ),
    ]
