# Generated by Django 5.1.2 on 2024-11-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_alarm_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='identification_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='input_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='led_pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
